### ISSUE TITLE
allennlp.common.checks.ConfigurationError: default not in acceptable choices for data_loader.type: ['pytorch_dataloader']

### ISSUE THREAD

**Issue by AslanDevbrat** [jacobdanovitch/allennlp_ranking_guide#1]
I am getting this error during `allennlp train` . Following is the complete error:

```
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/__init__.py", line 118, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 119, in train_model_from_args
    file_friendly_logging=args.file_friendly_logging,
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 178, in train_model_from_file
    file_friendly_logging=file_friendly_logging,
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 242, in train_model
    file_friendly_logging=file_friendly_logging,
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 456, in _train_worker
    local_rank=process_rank,
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/from_params.py", line 599, in from_params
    **extras,
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/from_params.py", line 629, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 686, in from_partial_objects
    data_loader_ = data_loader.construct(dataset=datasets["train"])
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/lazy.py", line 58, in construct
    return self._constructor(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/from_params.py", line 465, in constructor
    return value_cls.from_params(params=deepcopy(popped_params), **constructor_extras)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/from_params.py", line 579, in from_params
    default_to_first_choice=default_to_first_choice,
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/params.py", line 352, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: default not in acceptable choices for data_loader.type: ['pytorch_dataloader']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.
```

My library versions are:
```
allennlp==1.2.0
transformers==3.1.0
```

**Comment by AslanDevbrat** [comment]
I think changing the default parameter of the `dataloader`  in the configuration file to `pytorch_dataloader` will resolve this problem

**Comment by jacobdanovitch** [comment]
Hey, thanks for pointing this out! Yep, that's a version mismatch issue, that's changed in newer versions of allennlp. I'll add your PR and pin the requirements file this weekend. Were you able to get it working with that change?

**Comment by AslanDevbrat** [comment]
@jacobdanovitch Yes, It was working as expected after that Change. I have also created a pull request for that.
